individual_takeoff_platform:
  enabled: true

simulation_rate: 120.0 # Hz
clock_rate: 120.0 # Hz

uav_names: [
  "uav1",
]

uav1:
  type: "x500"
  spawn:
    x: 10.0
    y: 15.0
    z: 2.0
    heading: 0
