name: rostest

on:

  push:
    branches: [ master ]

    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

concurrency:
  group: rostest-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/rostest.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
