name: rostest

on:

  push:
    branches: [ master ]

    paths-ignore:
      - '**/README.md'

    pull_request:
      branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/rostest.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
